// Generated by CoffeeScript 1.8.0
(function() {
  var HatyuneMiku, ServoMotor, async, mainLoop, miku,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require('async');

  ServoMotor = (function() {
    ServoMotor.PWM_FREQUENCY = 50;

    ServoMotor.MAX_DUTY_CYCLE = 0.125;

    ServoMotor.MIN_DUTY_CYCLE = 0.025;

    function ServoMotor(pin_name) {
      this.move = __bind(this.move, this);
      this.tessel = require('tessel');
      this.gpio = this.tessel.port['GPIO'];
      this.gpio.pwmFrequency(ServoMotor.PWM_FREQUENCY);
      this.pin = this.gpio.pin[pin_name];
    }

    ServoMotor.prototype.move = function(angle) {
      var duty_cycle;
      if (!((0 <= angle && angle <= 180))) {
        console.log("invalid angle: " + angle);
        return false;
      }
      duty_cycle = ServoMotor.MIN_DUTY_CYCLE;
      duty_cycle += (angle / 180) * (ServoMotor.MAX_DUTY_CYCLE - ServoMotor.MIN_DUTY_CYCLE);
      this.pin.pwmDutyCycle(duty_cycle);
      console.log('servo angle: ' + angle);
      return true;
    };

    return ServoMotor;

  })();

  HatyuneMiku = (function(_super) {
    __extends(HatyuneMiku, _super);

    HatyuneMiku.UPPER_ANGLE = 100;

    HatyuneMiku.LOWER_ANGLE = 60;

    function HatyuneMiku(pin_name) {
      this.doNegifuri = __bind(this.doNegifuri, this);
      HatyuneMiku.__super__.constructor.call(this, pin_name);
      this.move(HatyuneMiku.LOWER_ANGLE);
    }

    HatyuneMiku.prototype.doNegifuri = function(repeat_count) {
      var repeated;
      console.log("doNegifuri repetition:" + repeat_count);
      repeated = 0;
      async.forever((function(_this) {
        return function(callback) {
          return async.series([
            function(callback) {
              _this.move(HatyuneMiku.UPPER_ANGLE);
              return setTimeout(callback, 400);
            }, function(callback) {
              _this.move(HatyuneMiku.LOWER_ANGLE);
              return setTimeout(callback, 400);
            }, function(callback) {
              if (++repeated < repeat_count) {
                return callback();
              }
            }
          ], callback);
        };
      })(this), function(err) {
        console.log(err);
        return false;
      });
      return true;
    };

    return HatyuneMiku;

  })(ServoMotor);

  miku = new HatyuneMiku('G4');

  mainLoop = function() {
    miku.doNegifuri(1);
    return setTimeout(mainLoop, 5000);
  };

  console.log('Tessel negifuri started!');

  setImmediate(mainLoop);

}).call(this);
